# تغير امس الملف الذي في المسار الاتي او حذف الملف 
# dashboard\views.py => views_old.py
# =======================

# ما تم التعديل عليه 
# ================================
# \baseer_project\dashboard
# =========
# dashboard\views  <== ملف جديد
# dashboard\models.py
# dashboard\urls.py
# dashboard\tests.py
# dashboard\ai_key_framework.py
# ================================
# baseer_project\baseer_project
# =========
# baseer_project\settings.py
# ================================
# baseer_project\templates\dashboard
# =========
# templates\dashboard\base.html
# templates\dashboard\ai_models.html

# تشغيل الاختبار الالي
# python manage.py test dashboard
# python manage.py test dashboard --nomigrations
# نظام الاختبار لا زال يعني من بعض المشاكل 